export function init(elem) {
    elem.focus();

    // Auto-resize whenever the user types or if the value is set programmatically
    elem.addEventListener('input', () => resizeToFit(elem));
    afterPropertyWritten(elem, 'value', () => resizeToFit(elem));

    // Auto-submit the form on 'enter' keypress
    elem.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            elem.dispatchEvent(new CustomEvent('change', { bubbles: true }));
            elem.closest('form').dispatchEvent(new CustomEvent('submit', { bubbles: true, cancelable: true }));
        }
    });
}

function resizeToFit(elem) {
    const lineHeight = parseFloat(getComputedStyle(elem).lineHeight);

    elem.rows = 1;
    const numLines = Math.ceil(elem.scrollHeight / lineHeight);
    elem.rows = Math.min(5, Math.max(1, numLines));
}

function afterPropertyWritten(target, propName, callback) {
    const descriptor = getPropertyDescriptor(target, propName);
    Object.defineProperty(target, propName, {
        get: function () {
            return descriptor.get.apply(this, arguments);
        },
        set: function () {
            const result = descriptor.set.apply(this, arguments);
            callback();
            return result;
        }
    });
}

function getPropertyDescriptor(target, propertyName) {
    return Object.getOwnPropertyDescriptor(target, propertyName)
        || getPropertyDescriptor(Object.getPrototypeOf(target), propertyName);
}

// SIG // Begin signature block
// SIG // MIIpQgYJKoZIhvcNAQcCoIIpMzCCKS8CAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // GfIRFZ6pOI3Uwod47vBdH/d1hXXSEGElRxfNVzonJqOg
// SIG // gg30MIIGcjCCBFqgAwIBAgITMwAABKuvOsiCTkhVXQAA
// SIG // AAAEqzANBgkqhkiG9w0BAQwFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI1MDkxODE3NTg1N1oX
// SIG // DTI2MDcwNjE3NTg1N1owYzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjENMAsGA1UEAxMELk5FVDCCAaIwDQYJKoZIhvcNAQEB
// SIG // BQADggGPADCCAYoCggGBAKQ4X+4WJICq9ogp+93S3ign
// SIG // Qhx+0SjWT/ZIdwwhDFj10Yfczf2kmMk593Z6IR+5G1Fb
// SIG // PQKk9YHI8vxLyK9K89H7AmPzyxu1tZnS5gqoD70m3sZA
// SIG // OI43mWo1H3KebvYI/abH6XZWAOekiOSx7yMEvA1LX3ge
// SIG // mWEaV0Otsd43VuWRRgmTjyFhiKHThv218roy1mTBbUXw
// SIG // 2gq6o3BcVsr8IalHQSS1U7v534eysUqzI11WlC0+ncUF
// SIG // 9r2ej0mdX61gLWSNZCKNdZ/mXXPMEhz2Q07iwdpAy6O6
// SIG // HNrASQnwfTRVnCn+TY/+E3BoBpUCV7Dg2UMTYJQlAsw7
// SIG // mEaaWSSW3a+S8aFC9unWFY0dNeRox6xl3vjTbzOMpXyr
// SIG // H+/0MDHGqaEO4vSbkIFLyVv6yxqOCtp/k0OcVcu20mBd
// SIG // cKQLKkK37CfjPg82u/8DT0cenCptF0BKVfahZ7lVah5Q
// SIG // lhOmDilG1KEelL+S/TXuj/tEp/MhgGWyvXi9VpwcmcET
// SIG // FSwUlwIDAQABo4IBgjCCAX4wHwYDVR0lBBgwFgYKKwYB
// SIG // BAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0OBBYEFLT595W9
// SIG // tJwzkjCnj1BmAzR7cFJvMFQGA1UdEQRNMEukSTBHMS0w
// SIG // KwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRp
// SIG // b25zIExpbWl0ZWQxFjAUBgNVBAUTDTQ2NDIyMys1MDYw
// SIG // OTAwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBDAUAA4ICAQAHYavo22iKWwSP
// SIG // Fqby97naAenHdlPya5n7g4LWyZURPwKJebBcYN5Ye/Om
// SIG // bkqpGYU9mwFZw6mdkhtP9voNSGhoAq1gsSasS9ni3832
// SIG // F5MP//pfk/vKkluVSti72uM3fqJnD/L/+Fnxg4blQIP4
// SIG // n83zfdSaUm3N1+4SMVsiMXcwbVnJ5xTWSn4bjCEljcfd
// SIG // 66JWujAWUVmjv4CG0SDO7ycJVuYfsY0iQbrkTRPepX1S
// SIG // TCuC3Hl+AYjWeUydM3YdH6G00PJPNOnPjKQdeSqbMXpp
// SIG // U3J3YQ1quEpoEaw6iQ/WDTrJTh4dwqS0mNWgu+nwSgFH
// SIG // EgHhQziOtPsqtatiDcfSAX8ScmimhOBPEUT/8OMP4llp
// SIG // gvUXQBa7cv3Uli4DS5vRbn3hyIFFQ2DyGSD5eRQI8T7q
// SIG // jC9DAX84zq2Q/dgw8Z6x2m9528a/1IeG4B2YEHIdOjMP
// SIG // cvF3fcZ8ocPo9Ek4VojynTBPN2NNBB66/dzysj5Ozg/P
// SIG // upGwvl2zhYDEqQtz1z7qQGyrMor7ce4yeiZoX7atCMX8
// SIG // GH94BhuFKx8q4mogSMzW1UINWMoRX/5rqKxZy4LUHnf/
// SIG // TAfcKhp+RUljdmkhqvtEb/DkyW/p/UunbuIjKXDjaDGP
// SIG // yqs51MNZ0H70DWM8yWf18sUjgsZaWC4hmTEmQcOU6le8
// SIG // CJVNG7jRZDCCB3owggVioAMCAQICCmEOkNIAAAAAAAMw
// SIG // DQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRp
// SIG // ZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTExMDcwODIw
// SIG // NTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0IENvZGUg
// SIG // U2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6qghBNNLry
// SIG // tlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vGEtgL8DjC
// SIG // mQawyDnVARQxQtOJDXlkh36UYCRsr55JnOloXtLfm1Oy
// SIG // CizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv56sIUM+z
// SIG // RLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5kNXimoGMP
// SIG // LdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vjK1oQH01W
// SIG // KKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd6IlPhBry
// SIG // oS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKdgCz1TlaR
// SIG // ITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBSv4yUh7zA
// SIG // IXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbsYR9q4ShJ
// SIG // nV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43BdD1FGd7P4
// SIG // AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhEfEXkwcNy
// SIG // euBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xbn6/83bBm
// SIG // 4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7IvhNdXnFy/
// SIG // dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMvdJX3bvh4
// SIG // IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY0uDWiIwL
// SIG // AgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEEAwIBADAd
// SIG // BgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1ApUwGQYJ
// SIG // KwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQD
// SIG // AgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
// SIG // ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBP
// SIG // oE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAxMV8y
// SIG // MDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYI
// SIG // KwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAxMV8yMDEx
// SIG // XzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGRBgkrBgEE
// SIG // AYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9wcmltYXJ5
// SIG // Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBMAGUAZwBh
// SIG // AGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQAZQBtAGUA
// SIG // bgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEAZ/KGpZjg
// SIG // VHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVfLiw++MNy
// SIG // 0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQfYtGUFXY
// SIG // DJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XUtR13lDni
// SIG // 6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELukqQUMm+1o
// SIG // +mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr3vw70L01
// SIG // 724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/DMhji8MUt
// SIG // zluetEk5CsYKwsatruWy2dsViFFFWDgycScaf7H0J/je
// SIG // LDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNNZgvAs031
// SIG // 4Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf2vP48hah
// SIG // mifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+YWG18NzG
// SIG // GwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOXpQlLSBCZ
// SIG // gB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r+0cjgPWe
// SIG // +L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6/IvrC4Dq
// SIG // aTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4ETIheu9B
// SIG // CrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBIa/15n8G9
// SIG // bW1qyVJzEw16UM0xghqmMIIaogIBATCBlTB+MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
// SIG // Q29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAEq686yIJO
// SIG // SFVdAAAAAASrMA0GCWCGSAFlAwQCAQUAoIGuMBkGCSqG
// SIG // SIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
// SIG // AQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEi
// SIG // BCBUYdb2w68QI5bZ81TaEACeiRT3Mreq9IvxyZ/4datj
// SIG // 0jBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBpAGMAcgBv
// SIG // AHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tMA0GCSqGSIb3DQEBAQUABIIBgEAhNT5LxzwW2SwY
// SIG // F1L+V9y6F1juyEaAovsCAPBl1//Nfhivww6WYTbKKLXv
// SIG // pZboASJf+zU91uN6du1G+AMaFYixIFdKhR8GDW5sWo+u
// SIG // LvZwdOMfGJvgTw0WJr+2TUGUb1dIlChtlxhEoJmB5nKi
// SIG // Rt7IrGXEoG4fTZz9PoTwouAmfh8sxkgbqOtwy14A7+9W
// SIG // 9VwiGdpDYEoAwbVWF8aOLC5+QIWIDAI+ka+kmsVUyj5s
// SIG // PjCm+kJd9aYkdTnFRvHcMoDCcKC+IO2VIfWiZLJAV3bH
// SIG // dEKlqbPnmczhAuvrcZValXI9Lugyy1kvYHXBDMpedQkq
// SIG // FeX+qeWc3RPkH6WA+xuo6wI4X3wJ49ooaznIYOII7SPK
// SIG // /7/4jlM8XSh6KfgXqlg6/n4TgQY9ctn9GLh7nJ7qanpi
// SIG // MjZ97nQCDSeGPJn9VrPRHa2htVDIxW1Szjqfks31Hntw
// SIG // bxRD1yXkRa80oLjSEp+vClGadHtr76tCiXDJ4XBfUivP
// SIG // BluRV3iKB70DLKGCF7AwghesBgorBgEEAYI3AwMBMYIX
// SIG // nDCCF5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJ
// SIG // YIZIAWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkE
// SIG // ggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
// SIG // AwQCAQUABCCpvScPIun1lsOkPud+lGQMA0dPJpVLqnEl
// SIG // MVLKw11kXQIGaQKOVHp0GBMyMDI1MTExMTA3NTMyNC43
// SIG // MTlaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBP
// SIG // cGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGll
// SIG // bGQgVFNTIEVTTjozMjFBLTA1RTAtRDk0NzElMCMGA1UE
// SIG // AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
// SIG // Ef4wggcoMIIFEKADAgECAhMzAAACGqmgHQagD0OqAAEA
// SIG // AAIaMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwMB4XDTI1MDgxNDE4NDgyOFoXDTI2
// SIG // MTExMzE4NDgyOFowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // LTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
// SIG // dGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBU
// SIG // U1MgRVNOOjMyMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxN
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmYEAwSTz
// SIG // 79q2V3ZWzQ5Ev7RKgadQtMBy7+V3XQ8R0NL8R9mupxcq
// SIG // JQ/KPeZGJTER+9Qq/t7HOQfBbDy6e0TepvBFV/RY3w+L
// SIG // OPMKn0Uoh2/8IvdSbJ8qAWRVoz2S9VrJzZpB8/f5rQcR
// SIG // ETgX/t8N66D2JlEXv4fZQB7XzcJMXr1puhuXbOt9RYEy
// SIG // N1Q3Z7YjRkhfBsRc+SD/C9F4iwZqfQgo82GG4wguIhjJ
// SIG // U7+XMfrv4vxAFNVg3mn1PoMWGZWio+e14+PGYPVLKlad
// SIG // +0IhdHK5AgPyXKkqAhEZpYhYYVEItHOOvqrwukxVAJXM
// SIG // vWA3GatWkRZn33WDJVtghCW6XPLi1cDKiGE5UcXZSV4O
// SIG // jQIUB8vp2LUMRXud5I49FIBcE9nT00z8A+EekrPM+OAk
// SIG // 07aDfwZbdmZ56j7ub5fNDLf8yIb8QxZ8Mr4RwWy/czBu
// SIG // V5rkWQQ+msjJ5AKtYZxJdnaZehUgUNArU/u36SH1eXKM
// SIG // QGRXr/xeKFGI8vvv5Jl1knZ8UqEQr9PxDbis7OXp2WSM
// SIG // K5lLGdYVH8VownYF3sbOiRkx5Q5GaEyTehOQp2SfdbsJ
// SIG // Zlg0SXmHphGnoW1/gQ/5P6BgSq4PAWIZaDJj6AvLLCdb
// SIG // URgR5apNQQed2zYUgUbjACA/TomA8Ll7Arrv2oZGiUO5
// SIG // Vdi4xxtA3BRTQTUCAwEAAaOCAUkwggFFMB0GA1UdDgQW
// SIG // BBTwqyIJ3QMoPasDcGdGovbaY8IlNjAfBgNVHSMEGDAW
// SIG // gBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBW
// SIG // MFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1w
// SIG // JTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEE
// SIG // YDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUy
// SIG // MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAM
// SIG // BgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
// SIG // BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEA1a72WFq7B6bJT3VOJ21nnToPJ9O/q51bw1bh
// SIG // PfQy67uy+f8x8akipzNL2k5b6mtxuPbZGpBqpBKguDwQ
// SIG // mxVpX8cGmafeo3wGr4a8Yk6Sy09tEh/Nwwlsyq7BRrJN
// SIG // n6bGOB8iG4OTy+pmMUh7FejNPRgvgeo/OPytm4NNrMMg
// SIG // 98UVlrZxGNOYsifpRJFg5jE/Yu6lqFa1lTm9cHuPYxWa
// SIG // 2oEwC0sEAsTFb69iKpN0sO19xBZCr0h5ClU9Pgo6ekiJ
// SIG // b7QJoDzrDoPQHwbNA87Cto7TLuphj0m9l/I70gLjEq53
// SIG // SHjuURzwpmNxdm18Qg+rlkaMC6Y2KukOfJ7oCSu9vcNG
// SIG // QM+inl9gsNgirZ6yJk9VsXEsoTtoR7fMNU6Py6ufJQGM
// SIG // Tmq6ZCq2eIGOXWMBb79ZF6tiKTa4qami3US0mTY41J12
// SIG // 9XmAglVy+ujSZkHu2lHJDRHs7FjnIXZVUE5pl6yUIl23
// SIG // jG50fRTLQcStdwY/LvJUgEHCIzjvlLTqLt6JVR5bcs5a
// SIG // N4Dh0YPG95B9iDMZrq4rli5SnGNWev5LLsDY1fbrK6uV
// SIG // pD+psvSLsNpht27QcHRsYdAMALXM+HNsz2LZ8xiOfwt6
// SIG // rOsVWXoiHV86/TeMy5TZFUl7qB59INoMSJgDRladVXeT
// SIG // 9fwOuirFIoqgjKGk3vO2bELrYMN0QVwwggdxMIIFWaAD
// SIG // AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3
// SIG // DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYD
// SIG // VQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBB
// SIG // dXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0z
// SIG // MDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
// SIG // CgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9Kp
// SIG // bE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5K
// SIG // Wv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTz
// SIG // xXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
// SIG // cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
// SIG // 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3K
// SIG // Ni1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3t
// SIG // pK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5Jas
// SIG // AUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ
// SIG // 1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHo
// SIG // vwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz
// SIG // 1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymei
// SIG // XtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8w
// SIG // dJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFd
// SIG // Etsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94
// SIG // q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0w
// SIG // ggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGC
// SIG // NxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1Ud
// SIG // DgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAE
// SIG // VTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
// SIG // FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYI
// SIG // KwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQw
// SIG // VgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEB
// SIG // BE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRf
// SIG // MjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIB
// SIG // AJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEG
// SIG // k5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi
// SIG // 7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce57
// SIG // 32pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OO
// SIG // PcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
// SIG // OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
// SIG // NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3m
// SIG // Sj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSw
// SIG // ethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23K
// SIG // jgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4
// SIG // S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFE
// SIG // fnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+
// SIG // pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/
// SIG // Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7t
// SIG // fqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJt
// SIG // pQUQwXEGahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEB
// SIG // oYHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYD
// SIG // VQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25z
// SIG // IExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjozMjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUA8YrutmKpSrubCaAYsU4pt1Ft8DaggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOy83fIwIhgPMjAyNTExMTAyMTU2
// SIG // MDJaGA8yMDI1MTExMTIxNTYwMlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA7Lzd8gIBADAKAgEAAgITUQIB/zAH
// SIG // AgEAAgIS+zAKAgUA7L4vcgIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQA14ZtC
// SIG // IZdiBsQuY08IxLW1hwDmmXXSdmtOiTAdd13jmjoEY1KP
// SIG // gcr44hoHL6wcWQc1kdZWDQ90vY7oLSw8d5gV07rSz89u
// SIG // YPW+gXFSmBumlEgWG2OWhs5XkNJ9G/6m9EVwaz0Rz9RK
// SIG // DHBXV9y9YxVMKr4eiLjehXee0lsf2hQyV1lhL97beQa5
// SIG // p7iPWJsCmcLTt+w+i0ILj2y76XjbNoLDukYlfH8mpZXt
// SIG // wNKzggwDxpymLus25Jh0SguQwfODTGWHnFo+gFwIiw6d
// SIG // 6m5WuyEDX3BHoLWheT4vf2JJh4CM9yzIbFqd/nfjee+3
// SIG // 6YECbR/iJNzL9GT+U42FSsoOZX0KMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAIaqaAdBqAPQ6oAAQAAAhowDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgGYTcW2O9KmpBiIDcLzqkqFll
// SIG // KXJ1+hPdOPUTpc5iA9kwgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCCdeiHHrbtpKcwB20doVU89WHIOH8S7
// SIG // w37uaHcDmemK+zCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAACGqmgHQagD0OqAAEAAAIa
// SIG // MCIEIKs0L8F4UNk8HE+42LkDuOA5XCldhSZ2bgsTcKmz
// SIG // 8CA1MA0GCSqGSIb3DQEBCwUABIICADcHQ2G5l+9qzLeY
// SIG // hA1A/URdrWQdeS9usqGl3F8ZYRLUBbAWvJ9gaNqxJK/i
// SIG // SQlOrsACXT1nf+Kt4k+CZ+j9QpxhVHBN7dsH3Cr7WZGQ
// SIG // tGGe31PlakOjnC08mgAHOH9q6+596fd49HkwUboXIobv
// SIG // SJHmdvghDXLQ+A616aHjTZdk4fMuWZUpbWEDL6wiI+s8
// SIG // VIsvkmcqmWkuWIYZS3wwjjiXE/NLXfd4xlMPe72DAVK1
// SIG // rULZaJA0kD694TgMcCWnOPmw+k27jlAtfi4sHUw9UqlV
// SIG // Eope4mbQ3QXk0qEqv60gqVIuA8COaN+9SpFSXBHZnGOp
// SIG // ZsgzmXwZousAVBBuhGSUOMsrB+WjSCeIgaD5VlNVN1xj
// SIG // e2L5i9JOywQD91WukSGLdAcps0oPL2WtWVa3veT0Iv2n
// SIG // nSX1j8Wh15OrF6YhQT+k0K77ozsprgSSAcvfi9PN0f56
// SIG // zSOYp9zSejlShgdZnFh6E3MWPb+9/5T0YtefGVVZccCJ
// SIG // Y6lplDU5gXx2Ha2swW5d4ciQ7f4EHBE2taz1Py1E+oqh
// SIG // cQyIT8w1F+TtMu8b0Nz/eEcRHzl0LY0Z0Hz6rrkUVGRl
// SIG // Vn4BLWCNEqLGxRNQMqvI7oUG/sjiH69CKn4kwV+8kQ75
// SIG // zhIlDkIzf3rWjl6vOUTuPZufDsuNPVL2Qtvi22hpfNRb
// SIG // 0OgamQh8
// SIG // End signature block
